-- V9__update_preset_avatars_to_wikipedia.sql
-- 将 36 个预设角色的头像 URL 从 DiceBear 抽象图替换为英文维基百科 220px 缩略图。
-- 仅作用于 is_preset=TRUE 的角色；用户自建角色不动。
-- DataLoader.seedCharactersIfMissing() 按名字幂等，跳过老库的角色，
-- 故新装的库靠 data.sql / DataLoader 自带的 avatar_url；已存在的库靠本脚本迁移。
-- 命名匹配使用 UTF-8 binary collation，name 列在建表时已用 utf8mb4。

UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Confucius_Tang_Dynasty.jpg/250px-Confucius_Tang_Dynasty.jpg'                       WHERE is_preset = TRUE AND name = '孔子';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Socrates_Louvre.jpg/250px-Socrates_Louvre.jpg'                                  WHERE is_preset = TRUE AND name = '苏格拉底';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Laozi_002.jpg/250px-Laozi_002.jpg'                                              WHERE is_preset = TRUE AND name = '老子';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Standing_Buddha_Gandhara._Mus%C3%A9e_des_arts_asiatiques_Guimet.jpg/250px-Standing_Buddha_Gandhara._Mus%C3%A9e_des_arts_asiatiques_Guimet.jpg' WHERE is_preset = TRUE AND name = '释迦牟尼';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Spas_vsederzhitel_sinay_%28cropped1%29.jpg/250px-Spas_vsederzhitel_sinay_%28cropped1%29.jpg' WHERE is_preset = TRUE AND name = '耶稣';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Al-Masjid_AL-Nabawi_Door.jpg/250px-Al-Masjid_AL-Nabawi_Door.jpg'             WHERE is_preset = TRUE AND name = '穆罕默德';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff/lossy-page1-250px-Galileo_Galilei_%281564-1642%29_RMG_BHC2700.tiff.jpg' WHERE is_preset = TRUE AND name = '伽利略';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Portrait_of_Sir_Isaac_Newton%2C_1689_%28brightened%29.jpg/250px-Portrait_of_Sir_Isaac_Newton%2C_1689_%28brightened%29.jpg' WHERE is_preset = TRUE AND name = '牛顿';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Charles_Darwin_seated_crop.jpg/250px-Charles_Darwin_seated_crop.jpg'              WHERE is_preset = TRUE AND name = '达尔文';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Albert_Einstein_Head_cleaned.jpg/250px-Albert_Einstein_Head_cleaned.jpg'        WHERE is_preset = TRUE AND name = '爱因斯坦';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Marie_Curie_c._1920s.jpg/250px-Marie_Curie_c._1920s.jpg'                          WHERE is_preset = TRUE AND name = '居里夫人';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Tesla_circa_1890.jpeg/250px-Tesla_circa_1890.jpeg'                              WHERE is_preset = TRUE AND name = '特斯拉';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/William_Shakespeare_by_John_Taylor%2C_edited.jpg/250px-William_Shakespeare_by_John_Taylor%2C_edited.jpg' WHERE is_preset = TRUE AND name = '莎士比亚';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Plato_Silanion_Musei_Capitolini_MC1377.png/250px-Plato_Silanion_Musei_Capitolini_MC1377.png' WHERE is_preset = TRUE AND name = '柏拉图';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Francesco_Melzi_-_Portrait_of_Leonardo.png/250px-Francesco_Melzi_-_Portrait_of_Leonardo.png' WHERE is_preset = TRUE AND name = '达·芬奇';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/YuanEmperorAlbumGenghisPortrait.jpg/250px-YuanEmperorAlbumGenghisPortrait.jpg' WHERE is_preset = TRUE AND name = '成吉思汗';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg/250px-Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg' WHERE is_preset = TRUE AND name = '拿破仑';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Mao_Zedong_1950_Portrait_%283x4_cropped%29%282%29.jpg/250px-Mao_Zedong_1950_Portrait_%283x4_cropped%29%282%29.jpg' WHERE is_preset = TRUE AND name = '毛泽东';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Aristotle_Altemps_Inv8575.jpg/250px-Aristotle_Altemps_Inv8575.jpg'              WHERE is_preset = TRUE AND name = '亚里士多德';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Karl_Marx_by_John_Jabez_Edwin_Mayall_1875_-_Restored_%26_Adjusted_%283x4_cropped_b%29.png/250px-Karl_Marx_by_John_Jabez_Edwin_Mayall_1875_-_Restored_%26_Adjusted_%283x4_cropped_b%29.png' WHERE is_preset = TRUE AND name = '马克思';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Lenin_in_1920_%28cropped%29.jpg/250px-Lenin_in_1920_%28cropped%29.jpg'          WHERE is_preset = TRUE AND name = '列宁';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Maurice_Quentin_de_La_Tour_-_Portrait_of_Jean-Jacques_Rousseau_-_adjusted.jpg/250px-Maurice_Quentin_de_La_Tour_-_Portrait_of_Jean-Jacques_Rousseau_-_adjusted.jpg' WHERE is_preset = TRUE AND name = '卢梭';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Nicolas_de_Largilli%C3%A8re_-_Portrait_de_Voltaire_%281694-1778%29_en_1718_-_P208_-_mus%C3%A9e_Carnavalet_-_5_%28cropped%29.jpg/250px-Nicolas_de_Largilli%C3%A8re_-_Portrait_de_Voltaire_%281694-1778%29_en_1718_-_P208_-_mus%C3%A9e_Carnavalet_-_5_%28cropped%29.jpg' WHERE is_preset = TRUE AND name = '伏尔泰';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Immanuel_Kant_-_Gemaelde_1.jpg/250px-Immanuel_Kant_-_Gemaelde_1.jpg'              WHERE is_preset = TRUE AND name = '康德';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Jakob_Schlesinger_-_Hegel_1831.jpg/250px-Jakob_Schlesinger_-_Hegel_1831.jpg'   WHERE is_preset = TRUE AND name = '黑格尔';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nietzsche187a.jpg/250px-Nietzsche187a.jpg'                                        WHERE is_preset = TRUE AND name = '尼采';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Sigmund_Freud%2C_by_Max_Halberstadt_%28cropped%29.jpg/250px-Sigmund_Freud%2C_by_Max_Halberstadt_%28cropped%29.jpg' WHERE is_preset = TRUE AND name = '弗洛伊德';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Evariste_galois.jpg/250px-Evariste_galois.jpg'                                  WHERE is_preset = TRUE AND name = '伽罗瓦';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Carl_Friedrich_Gauss_1840_by_Jensen.jpg/250px-Carl_Friedrich_Gauss_1840_by_Jensen.jpg' WHERE is_preset = TRUE AND name = '高斯';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/James-Clerk-Maxwell-1831-1879.jpg/250px-James-Clerk-Maxwell-1831-1879.jpg'     WHERE is_preset = TRUE AND name = '麦克斯韦';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Niels_Bohr.jpg/250px-Niels_Bohr.jpg'                                              WHERE is_preset = TRUE AND name = '玻尔';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Werner_Heisenberg_Portrait_%283x4_cropped%29.jpg/250px-Werner_Heisenberg_Portrait_%283x4_cropped%29.jpg' WHERE is_preset = TRUE AND name = '海森堡';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Johann_Sebastian_Bach.jpg/250px-Johann_Sebastian_Bach.jpg'                       WHERE is_preset = TRUE AND name = '巴赫';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/The_Mozart_Family_-_Wolfgang_Amadeus_Mozart_headshot.jpg/250px-The_Mozart_Family_-_Wolfgang_Amadeus_Mozart_headshot.jpg' WHERE is_preset = TRUE AND name = '莫扎特';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg/250px-Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg' WHERE is_preset = TRUE AND name = '贝多芬';
UPDATE characters SET avatar_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/250px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg' WHERE is_preset = TRUE AND name = '梵高';
