-- V10 之后：本文件不再写入任何 preset 角色。
-- 预设角色（120 个：孔子/爱因斯坦/贝多芬 等）的权威数据已迁移到
-- classpath:presets.json（详见 PresetCharacterCache）。
-- V10 migration 在部署时执行物理删除 120 条 preset，
-- 此后本文件保持空（不再需要 INSERT IGNORE 兜底）。
--
-- 如需重新植入 preset：恢复旧 data.sql 即可。
-- 未来若走"管理后台编辑"路径，应改用 AdminPresetService + cache.reload()。
